### PR TITLE
Project: Restaurant Page

### PR DESCRIPTION
**Pull request by SmithVyne**
**What does this PR do?**
This is for the TSE review of the project implementation.

**Live version**
[https://vyne-restaurant.netlify.app/](https://vyne-restaurant.netlify.app/)

**How can this be manually tested?**
Clone the repository from a terminal https://github.com/SmithVyne/Restaurant__Page.git
Navigate to the project directory `cd restaurant__page`
Install project dependencies with `npm install`
Run `npm run webpack` to compile a development build and start watching for any changes too.
Assignment Specs

https://www.theodinproject.com/courses/javascript/lessons/restaurant-page

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @SmithVyne, great effort on this project :+1: However, there are a couple of issues we need to address before we can approve the project :slightly_smiling_face: Kindly check the comments below and address it accordingly:
- `README file` our project is missing one important element, which is the README file. This is where we get to understand the project and if possible run and test it. Let us add a descriptive README to our project
- `Package.json` file, is missing an import element, which is the scripts. You mentioned in the PR to run `npm run webpack` but we do not have that script in the file. Kindly replace your script with this
 ```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
 I could not run the project locally due to this error `missing script: webpack` following the PR instructions
- Since this is a Javascript project, let us strictly use `document.createElement` for creating our HTML elements and `document.appendChild` for appending child elements to parents. Let us change our code accordingly. Example code below:
```javascript
const myModule = (parentNode) => {
    const node = document.createElement('div');
    // Add whichever sub-nodes, ids and style is required

    parentNode.appendChild(node);
};

export { myModule as default };
```
- It features a tabbed menu. When a tab is clicked the content is replaced
- The contents of each tab are stored in a `module`
- Each `module` exports a function that creates a `<div>` element, adds the appropriate content and styles to that element, and then appends it to the DOM.
- Let us kindly add `webpack-dev-server` to the devDependencies of our package.json file

Kindly submit another code review once these comments are resolved :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light:  

Hi @SmithVyne, great job fixing most of the comments :+1: 2 of the requirements were not addressed. Kindly address them since they are requirements and cannot be approved without fixing them. I will outline those comments below:
- `Package.json` file must have the following scripts
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```
The third one is optional. It is great to be creative, but this is a requirement
- `Home, Menu, Contact` should be wrapped in a module as in the screenshot below
tnb
For example; `const home = () => { } const menu = () => {}  const contact = () => {}`

Once this is addressed, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Review by rOluochKe — APPROVED** [review]
Hello @SmithVyne 
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

### [Improvements]
- You can add start option in the scripts, see below
`"start": "webpack-dev-server --mode development --open"`

**Comment by SmithVyne** [comment]
Thank you @rOluochKe for your review

**Pull request merged**
